services:

- type: web
  name: n8n
  runtime: docker
  plan: free
  
  image:
  url: docker.io/n8nio/n8n
  
  envVars:
  
  - key: N8N_HOST
    value: localhost
  
  - key: WEBHOOK_URL
    value: https://localhost
  
  - key: GENERIC_TIMEZONE
    value: Asia/Karachi
  
  - key: N8N_BASIC_AUTH_ACTIVE
    value: "true"
  
  - key: N8N_BASIC_AUTH_USER
    value: admin
  
  - key: N8N_BASIC_AUTH_PASSWORD
    value: admin123
