services:

- type: web
  name: n8n
  runtime: image
  image:
  url: n8nio/n8n
  
  plan: free
  
  envVars:
  
  - key: N8N_BASIC_AUTH_ACTIVE
    value: true
  
  - key: N8N_BASIC_AUTH_USER
    value: admin
  
  - key: N8N_BASIC_AUTH_PASSWORD
    value: admin123
  
  - key: GENERIC_TIMEZONE
    value: Asia/Karachi
